### ISSUE TITLE
Product Not Available on selecting a disabled variant not reloading product partial

### ISSUE THREAD

**Issue by aperdomo** [lemonstand/lscloud-theme-happyhour#4]
### Steps To Reproduce
1. Disable a variant for a product.
2. Navigate to its product page.
3. Try selecting the item.

Compare against Zest for desired behaviour.

**Comment by af19** [comment]
Zest doesn't have the desired behaviour.

![screen shot 2016-02-29 at 3 04 22 pm](https://cloud.githubusercontent.com/assets/7540725/13412094/cb1b704c-def5-11e5-92e3-10d4d4db6a01.png)
